package multi

import (
	"github.com/mark3labs/mcp-go/mcp"

	"github.com/bearaujus/bmcptools/internal/asset"
	"github.com/bearaujus/bmcptools/pkg/toolname"
	"github.com/bearaujus/bmcptools/pkg/toolreg"
)

// Register registers all multi-file tools with s.
func Register(s toolreg.ToolRegistrar) {
	s.AddTool(mcp.NewTool(toolname.ReadMultipleFiles,
		mcp.WithDescription(asset.ToolDesc(toolname.ReadMultipleFiles)),
		mcp.WithReadOnlyHintAnnotation(true),
		mcp.WithArray("paths",
			mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "paths")),
			mcp.Items(map[string]any{
				"anyOf": []any{
					map[string]any{"type": "string"},
					map[string]any{
						"type": "object",
						"properties": map[string]any{
							"path":              map[string]any{"type": "string", "description": "File path to read"},
							"start_line":        map[string]any{"type": "number", "description": "First line to read, 1-indexed"},
							"end_line":          map[string]any{"type": "number", "description": "Last line to read, inclusive"},
							"head":              map[string]any{"type": "number", "description": "Return only the first N lines"},
							"tail":              map[string]any{"type": "number", "description": "Return only the last N lines"},
							"show_line_numbers": map[string]any{"type": "boolean", "description": "Prefix output lines with source line numbers"},
							"max_bytes":         map[string]any{"type": "number", "description": "Maximum bytes to return for this file"},
							"ranges": map[string]any{
								"type": "array",
								"items": map[string]any{
									"type":  "array",
									"items": map[string]any{"type": "number"},
								},
							},
						},
						"required": []string{"path"},
					},
				},
			}),
		),
		mcp.WithNumber("max_bytes_per_file",
			mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "max_bytes_per_file")),
		),
		mcp.WithNumber("total_max_bytes",
			mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "total_max_bytes")),
		),
		mcp.WithBoolean("include_base64",
			mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "include_base64")),
		),
		mcp.WithString("root",
			mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "root")),
		),
		mcp.WithString("glob",
			mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "glob")),
		),
		mcp.WithBoolean("recursive",
			mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "recursive")),
		),
		mcp.WithBoolean("show_hidden",
			mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "show_hidden")),
		),
		mcp.WithArray("exclude_patterns",
			mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "exclude_patterns")),
			mcp.Items(map[string]any{"type": "string"}),
		),
		mcp.WithNumber("start_line", mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "start_line"))),
		mcp.WithNumber("end_line", mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "end_line"))),
		mcp.WithNumber("head", mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "head"))),
		mcp.WithNumber("tail", mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "tail"))),
		mcp.WithBoolean("show_line_numbers", mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "show_line_numbers"))),
		mcp.WithArray("ranges",
			mcp.Description(asset.ParamDesc(toolname.ReadMultipleFiles, "ranges")),
			mcp.Items(map[string]any{
				"type":  "array",
				"items": map[string]any{"type": "number"},
			}),
		),
	), readMultipleFilesHandler)

	s.AddTool(mcp.NewTool(toolname.WriteMultipleFiles,
		mcp.WithDescription(asset.ToolDesc(toolname.WriteMultipleFiles)),
		mcp.WithDestructiveHintAnnotation(true),
		mcp.WithIdempotentHintAnnotation(true),
		mcp.WithArray("files",
			mcp.Required(),
			mcp.Description(asset.ParamDesc(toolname.WriteMultipleFiles, "files")),
			mcp.Items(map[string]any{
				"type": "object",
				"properties": map[string]any{
					"path":    map[string]any{"type": "string", "description": "File path to write"},
					"content": map[string]any{"type": "string", "description": "Content to write"},
				},
				"required": []string{"path", "content"},
			}),
		),
		mcp.WithBoolean("create_dirs",
			mcp.Description(asset.ParamDesc(toolname.WriteMultipleFiles, "create_dirs")),
		),
		mcp.WithBoolean("show_diff",
			mcp.Description(asset.ParamDesc(toolname.WriteMultipleFiles, "show_diff")),
		),
		mcp.WithBoolean("all_or_nothing",
			mcp.Description(asset.ParamDesc(toolname.WriteMultipleFiles, "all_or_nothing")),
		),
	), writeMultipleFilesHandler)

	s.AddTool(mcp.NewTool(toolname.FindReplaceInFiles,
		mcp.WithDescription(asset.ToolDesc(toolname.FindReplaceInFiles)),
		mcp.WithDestructiveHintAnnotation(true),
		mcp.WithString("path",
			mcp.Required(),
			mcp.Description(asset.ParamDesc(toolname.FindReplaceInFiles, "path")),
		),
		mcp.WithString("old_str",
			mcp.Required(),
			mcp.Description(asset.ParamDesc(toolname.FindReplaceInFiles, "old_str")),
		),
		mcp.WithString("new_str",
			mcp.Required(),
			mcp.Description(asset.ParamDesc(toolname.FindReplaceInFiles, "new_str")),
		),
		mcp.WithBoolean("use_regex",
			mcp.Description(asset.ParamDesc(toolname.FindReplaceInFiles, "use_regex")),
		),
		mcp.WithBoolean("recursive",
			mcp.Description(asset.ParamDesc(toolname.FindReplaceInFiles, "recursive")),
		),
		mcp.WithString("glob",
			mcp.Description(asset.ParamDesc(toolname.FindReplaceInFiles, "glob")),
		),
		mcp.WithBoolean("dry_run",
			mcp.Description(asset.ParamDesc(toolname.FindReplaceInFiles, "dry_run")),
		),
		mcp.WithBoolean("show_diff",
			mcp.Description(asset.ParamDesc(toolname.FindReplaceInFiles, "show_diff")),
		),
		mcp.WithBoolean("show_hidden",
			mcp.Description(asset.ParamDesc(toolname.FindReplaceInFiles, "show_hidden")),
		),
		mcp.WithArray("exclude_patterns",
			mcp.Description(asset.ParamDesc(toolname.FindReplaceInFiles, "exclude_patterns")),
			mcp.Items(map[string]any{"type": "string"}),
		),
		mcp.WithBoolean("show_unmodified",
			mcp.Description(asset.ParamDesc(toolname.FindReplaceInFiles, "show_unmodified")),
		),
		mcp.WithNumber("max_file_size",
			mcp.Description(asset.ParamDesc(toolname.FindReplaceInFiles, "max_file_size")),
		),
		mcp.WithNumber("max_total_diff_bytes",
			mcp.Description(asset.ParamDesc(toolname.FindReplaceInFiles, "max_total_diff_bytes")),
		),
	), findReplaceInFilesHandler)

	s.AddTool(mcp.NewTool(toolname.PathExistsBatch,
		mcp.WithDescription(asset.ToolDesc(toolname.PathExistsBatch)),
		mcp.WithReadOnlyHintAnnotation(true),
		mcp.WithArray("paths",
			mcp.Required(),
			mcp.Description(asset.ParamDesc(toolname.PathExistsBatch, "paths")),
			mcp.Items(map[string]any{"type": "string"}),
		),
		mcp.WithNumber("limit",
			mcp.Description(asset.ParamDesc(toolname.PathExistsBatch, "limit")),
		),
	), pathExistsBatchHandler)

	s.AddTool(mcp.NewTool(toolname.GetMultipleFileInfo,
		mcp.WithDescription(asset.ToolDesc(toolname.GetMultipleFileInfo)),
		mcp.WithReadOnlyHintAnnotation(true),
		mcp.WithArray("paths",
			mcp.Required(),
			mcp.Description(asset.ParamDesc(toolname.GetMultipleFileInfo, "paths")),
			mcp.Items(map[string]any{"type": "string"}),
		),
		mcp.WithNumber("limit",
			mcp.Description(asset.ParamDesc(toolname.GetMultipleFileInfo, "limit")),
		),
		mcp.WithBoolean("count_lines",
			mcp.Description(asset.ParamDesc(toolname.GetMultipleFileInfo, "count_lines")),
		),
		mcp.WithString("output_mode",
			mcp.Description(asset.ParamDesc(toolname.GetMultipleFileInfo, "output_mode")),
		),
	), getMultipleFileInfoHandler)

	s.AddTool(mcp.NewTool(toolname.DeleteFiles,
		mcp.WithDescription(asset.ToolDesc(toolname.DeleteFiles)),
		mcp.WithDestructiveHintAnnotation(true),
		mcp.WithArray("paths",
			mcp.Required(),
			mcp.Description(asset.ParamDesc(toolname.DeleteFiles, "paths")),
			mcp.Items(map[string]any{"type": "string"}),
		),
	), deleteFilesHandler)

	s.AddTool(mcp.NewTool(toolname.CopyPaths,
		mcp.WithDescription(asset.ToolDesc(toolname.CopyPaths)),
		mcp.WithDestructiveHintAnnotation(true),
		mcp.WithArray("entries",
			mcp.Required(),
			mcp.Description(asset.ParamDesc(toolname.CopyPaths, "entries")),
			mcp.Items(map[string]any{
				"type": "object",
				"properties": map[string]any{
					"source":      map[string]any{"type": "string", "description": "Source file or directory path"},
					"destination": map[string]any{"type": "string", "description": "Destination path"},
					"overwrite":   map[string]any{"type": "boolean", "description": "Override the shared overwrite default for this entry"},
				},
				"required": []string{"source", "destination"},
			}),
		),
		mcp.WithBoolean("overwrite",
			mcp.Description(asset.ParamDesc(toolname.CopyPaths, "overwrite")),
		),
	), copyPathsHandler)

	s.AddTool(mcp.NewTool(toolname.MovePaths,
		mcp.WithDescription(asset.ToolDesc(toolname.MovePaths)),
		mcp.WithDestructiveHintAnnotation(true),
		mcp.WithArray("entries",
			mcp.Required(),
			mcp.Description(asset.ParamDesc(toolname.MovePaths, "entries")),
			mcp.Items(map[string]any{
				"type": "object",
				"properties": map[string]any{
					"source":      map[string]any{"type": "string", "description": "Source file or directory path"},
					"destination": map[string]any{"type": "string", "description": "Destination path"},
					"overwrite":   map[string]any{"type": "boolean", "description": "Override the shared overwrite default for this entry"},
				},
				"required": []string{"source", "destination"},
			}),
		),
		mcp.WithBoolean("overwrite",
			mcp.Description(asset.ParamDesc(toolname.MovePaths, "overwrite")),
		),
	), movePathsHandler)
}
